### ISSUE TITLE
[BUG] Plugins do not get deleted upon uninstall / update

### ISSUE THREAD

**Issue by hugalafutro** [linuxserver/docker-jellyfin#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you uninstall a plugin it remains in the data volume. If you update a plaugin the old version stays along the new one. I'm not sure whether it's a docker issue or Jellyfin issue and figured I have 50/50 chance of reporting it in the right place.
```
sammael@vm-docker:~/docker/vpn-stack$ ls -la library_jellyfin/data/plugins/
total 128
drwxr-xr-x 32 sammael sammael 4096 Jan 15 09:43  .
drwxr-xr-x  7 sammael sammael 4096 Nov 14  2020  ..
drwxr-xr-x  2 sammael sammael 4096 Sep  8  2021  AniDB_4.0.0.0
drwxr-xr-x  2 sammael sammael 4096 Jun 11  2022  AniDB_6.0.0.0
drwxr-xr-x  2 sammael sammael 4096 Jul 10  2022  AniDB_7.0.0.0
drwxr-xr-x  2 sammael sammael 4096 Sep 22  2021  AniList_4.0.0.0
drwxr-xr-x  2 sammael sammael 4096 Jun 11  2022  AniList_5.0.0.0
drwxr-xr-x  2 sammael sammael 4096 Jul 28  2021 'Cover Art Archive_3.0.0.0'
drwxr-xr-x  2 sammael sammael 4096 Jun 11  2022 'Cover Art Archive_7.0.0.0'
drwxr-xr-x  2 sammael sammael 4096 Jun 12  2022  Fanart_10.0.0.0
drwxr-xr-x  2 sammael sammael 4096 Sep  3  2021  Fanart_7.0.0.0
drwxr-xr-x  2 sammael sammael 4096 Jun 11  2022  Fanart_9.0.0.0
drwxr-xr-x  2 sammael sammael 4096 Nov  2  2021  Kitsu_2.0.0.0
drwxr-xr-x  2 sammael sammael 4096 Jun 11  2022  Kitsu_3.0.0.0
drwxr-xr-x  2 sammael sammael 4096 Jun 13  2022  Kitsu_4.0.0.0
drwxr-xr-x  2 sammael sammael 4096 Dec 12  2021 'Kodi Sync Queue_6.0.0.0'
drwxr-xr-x  2 sammael sammael 4096 Jun 11  2022 'Kodi Sync Queue_8.0.0.0'
drwxr-xr-x  2 sammael sammael 4096 Aug  7 17:21 'Kodi Sync Queue_9.0.0.0'
drwxr-xr-x  2 sammael sammael 4096 Nov 15  2021 'Playback Reporting_10.0.0.0'
drwxr-xr-x  2 sammael sammael 4096 Jun 11  2022 'Playback Reporting_12.0.0.0'
drwxr-xr-x  2 sammael sammael 4096 Jan 15 09:43 'Playback Reporting_13.0.0.0'
drwxr-xr-x  2 sammael sammael 4096 Jan 15 09:42  Reports_15.0.0.0
drwxr-xr-x  2 sammael sammael 4096 Apr 10  2021 'Session Cleaner_1.2021.117.2130'
drwxr-xr-x  2 sammael sammael 4096 Jun 11  2022 'Session Cleaner_2.0.0.0'
drwxr-xr-x  2 sammael sammael 4096 Oct 16 12:39 'Skin Manager_2.0.1'
drwxr-xr-x  2 sammael sammael 4096 Oct 16 12:38 'Subtitle Extract_2.0.0.0'
drwxr-xr-x  2 sammael sammael 4096 Jun 11  2022 'TMDb Box Sets_10.0.0.0'
drwxr-xr-x  2 sammael sammael 4096 Mar 11  2021 'TMDb Box Sets_7.0.0.0'
drwxr-xr-x  2 sammael sammael 4096 Sep  6  2021 'TV Maze_5.0.0.0'
drwxr-xr-x  2 sammael sammael 4096 Aug  8  2021  TheTVDB_6.0.0.0
drwxr-xr-x  2 sammael sammael 4096 Jun 11  2022  TheTVDB_8.0.0.0
drwxr-xr-x  2 sammael sammael 4096 Jun 11  2022  configurations

```

### Expected Behavior

Uninstalled plugin should disappear, updated addon should retain only the latest version

### Steps To Reproduce

1. Uninstall or Update any plugin in Jellyfin ls.io docker image
2. restart container
3. observe the files remained

### Environment

```markdown
- OS: ubuntu vm
- How docker service was installed: apt
```

### CPU architecture

x86-64

### Docker creation

```bash
jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=192.168.1.249
    volumes:
      - ./library_jellyfin:/config
      - /shares/samba/media:/media
      - /shares/samba/media2:/media2
      - /shares/nfs/private/_tube-archivist:/tube-archivist:ro
    ports:
      - 8096:8096
    restart: always
    stop_grace_period: 60s
    labels:
      containermon.enable: true
```

### Container logs

```bash
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Jellyfin: https://opencollective.com/jellyfin

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[custom-init] No custom files found, skipping...
[09:43:14] [INF] [1] Main: Jellyfin version: 10.8.8
[09:43:14] [INF] [1] Main: Environment Variables: ["[JELLYFIN_PublishedServerUrl, 192.168.1.249]", "[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_DATA_DIR, /config/data]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_WEB_DIR, /usr/share/jellyfin/web]"]
[09:43:14] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[09:43:14] [INF] [1] Main: Operating system: Linux
[09:43:14] [INF] [1] Main: Architecture: X64
[09:43:14] [INF] [1] Main: 64-Bit Process: True
[09:43:14] [INF] [1] Main: User Interactive: True
[09:43:14] [INF] [1] Main: Processor count: 12
[09:43:14] [INF] [1] Main: Program data path: /config/data
[09:43:14] [INF] [1] Main: Web resources path: /usr/share/jellyfin/web
[09:43:14] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[09:43:15] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /config/cache
[09:43:15] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.AniDB, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/AniDB_7.0.0.0/Jellyfin.Plugin.AniDB.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.AniList, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/AniList_5.0.0.0/Jellyfin.Plugin.AniList.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly MetaBrainz.MusicBrainz.CoverArt, Version=4.0.0.0, Culture=neutral, PublicKeyToken=be12cbb629c03021 from /config/data/plugins/Cover Art Archive_7.0.0.0/MetaBrainz.MusicBrainz.CoverArt.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly MetaBrainz.Common.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=be12cbb629c03021 from /config/data/plugins/Cover Art Archive_7.0.0.0/MetaBrainz.Common.Json.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.CoverArtArchive, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Cover Art Archive_7.0.0.0/Jellyfin.Plugin.CoverArtArchive.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Fanart, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Fanart_10.0.0.0/Jellyfin.Plugin.Fanart.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Kitsu, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Kitsu_4.0.0.0/Jellyfin.Plugin.Kitsu.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.KodiSyncQueue, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Kodi Sync Queue_9.0.0.0/Jellyfin.Plugin.KodiSyncQueue.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly LiteDB, Version=5.0.12.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27 from /config/data/plugins/Kodi Sync Queue_9.0.0.0/LiteDB.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Playback Reporting_12.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Reports, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Reports_15.0.0.0/Jellyfin.Plugin.Reports.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.SessionCleaner, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Session Cleaner_2.0.0.0/Jellyfin.Plugin.SessionCleaner.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.SkinManager, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Skin Manager_2.0.1/Jellyfin.Plugin.SkinManager.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.SubtitleExtract, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Subtitle Extract_2.0.0.0/Jellyfin.Plugin.SubtitleExtract.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Tvdb, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TheTVDB_8.0.0.0/Jellyfin.Plugin.Tvdb.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly TvDbSharper, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TheTVDB_8.0.0.0/TvDbSharper.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.TMDbBoxSets, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TMDb Box Sets_10.0.0.0/Jellyfin.Plugin.TMDbBoxSets.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.TvMaze, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TV Maze_5.0.0.0/Jellyfin.Plugin.TvMaze.dll
[09:43:15] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly TvMaze.Api.Client, Version=0.0.33.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TV Maze_5.0.0.0/TvMaze.Api.Client.dll
[09:43:15] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [fc00::/7,fe80::/10,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[09:43:15] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[09:43:15] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [fc00::/7,fe80::/10,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[09:43:15] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[09:43:15] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AniDB 7.0.0.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AniList 5.0.0.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Cover Art Archive 7.0.0.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Fanart 10.0.0.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Kitsu 4.0.0.0
[09:43:27] [INF] [1] Jellyfin.Plugin.KodiSyncQueue.KodiSyncQueuePlugin: KodiSyncQueue is starting...
[09:43:27] [INF] [1] Jellyfin.Plugin.KodiSyncQueue.Data.DbRepo: Creating DB Repository...
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Kodi Sync Queue 9.0.0.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Playback Reporting 12.0.0.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Reports 15.0.0.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Session Cleaner 2.0.0.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Skin Manager 2.0.1
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Subtitle Extract 2.0.0.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TheTVDB 8.0.0.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb Box Sets 10.0.0.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TV Maze 5.0.0.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.8.8.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.8.8.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.8.8.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.8.8.0
[09:43:27] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.8.8.0
[09:43:27] [INF] [1] Main: Kestrel listening on All Addresses
[09:43:27] [WRN] [1] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
[09:43:27] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[09:43:27] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {005613b4-d553-4faa-b95a-81d5f2f312c5} may be persisted to storage in unencrypted form.
[09:43:27] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[09:43:27] [INF] [1] Jellyfin.Plugin.KodiSyncQueue.ScheduledTasks.RetentionTask: Retention task scheduled
[09:43:27] [INF] [1] Jellyfin.Plugin.PlaybackReporting.TaskCleanDb: TaskCleanDb Loaded
[09:43:27] [INF] [1] Jellyfin.Plugin.PlaybackReporting.TaskRunBackup: TaskRunBackup Loaded
[09:43:27] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Remove Old Sync Data set to fire at 2023-01-16 00:01:00.000 +00:00, which is 14:17:32.2295278 from now.
[09:43:27] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Playback Reporting Trim Db set to fire at 2023-01-16 00:00:00.000 +00:00, which is 14:16:32.2282219 from now.
[09:43:27] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Clean Old Sessions set to fire at 2023-01-16 00:00:00.000 +00:00, which is 14:16:32.2170130 from now.
[09:43:27] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Subtitle Extract set to fire at 2023-01-16 02:45:00.000 +00:00, which is 17:01:32.2162835 from now.
[09:43:27] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 2023-01-16 02:00:00.000 +00:00, which is 16:16:32.2058999 from now.
[09:43:27] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Keyframe Extractor set to fire at 2023-01-16 01:15:00.000 +00:00, which is 15:31:32.1914973 from now.
[09:43:27] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 5.1.2
[09:43:27] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[09:43:27] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[09:43:27] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "hwupload_vaapi", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[09:43:28] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[ls.io-init] done.
[09:43:28] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: /usr/lib/jellyfin-ffmpeg/ffmpeg
[09:43:28] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: 1dd0b01f64234b3b9262efd311b82436
[09:43:28] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.0838422
[09:43:28] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[09:43:28] [INF] [1] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: EventMonitorEntryPoint Running
[09:43:28] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Sqlite version: 3.38.3
[09:43:28] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Sqlite compiler options: ATOMIC_INTRINSICS=1,COMPILER=gcc-7.5.0,DEFAULT_AUTOVACUUM,DEFAULT_CACHE_SIZE=-2000,DEFAULT_FILE_FORMAT=4,DEFAULT_FOREIGN_KEYS,DEFAULT_JOURNAL_SIZE_LIMIT=-1,DEFAULT_MMAP_SIZE=0,DEFAULT_PAGE_SIZE=4096,DEFAULT_PCACHE_INITSZ=20,DEFAULT_RECURSIVE_TRIGGERS,DEFAULT_SECTOR_SIZE=4096,DEFAULT_SYNCHRONOUS=2,DEFAULT_WAL_AUTOCHECKPOINT=1000,DEFAULT_WAL_SYNCHRONOUS=2,DEFAULT_WORKER_THREADS=0,ENABLE_COLUMN_METADATA,ENABLE_FTS3,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS4,ENABLE_FTS5,ENABLE_RTREE,ENABLE_SNAPSHOT,MALLOC_SOFT_LIMIT=1024,MAX_ATTACHED=10,MAX_COLUMN=2000,MAX_COMPOUND_SELECT=500,MAX_DEFAULT_PAGE_SIZE=8192,MAX_EXPR_DEPTH=1000,MAX_FUNCTION_ARG=127,MAX_LENGTH=1000000000,MAX_LIKE_PATTERN_LENGTH=50000,MAX_MMAP_SIZE=0x7fff0000,MAX_PAGE_COUNT=1073741823,MAX_PAGE_SIZE=65536,MAX_SQL_LENGTH=1000000000,MAX_TRIGGER_DEPTH=1000,MAX_VARIABLE_NUMBER=32766,MAX_VDBE_OP=250000000,MAX_WORKER_THREADS=8,MUTEX_PTHREADS,SYSTEM_MALLOC,TEMP_STORE=1,THREADSAFE=1
[09:43:28] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Default journal_mode for /config/data/data/playback_reporting.db is delete
[09:43:28] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Initialize PlaybackActivity Repository
[09:43:28] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: PlaybackActivity table schema OK
[09:43:28] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Expected : datecreated:datetime|userid:text|itemid:text|itemtype:text|itemname:text|playbackmethod:text|clientname:text|devicename:text|playduration:int
[09:43:28] [INF] [1] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Received : datecreated:datetime|userid:text|itemid:text|itemtype:text|itemname:text|playbackmethod:text|clientname:text|devicename:text|playduration:int
[09:43:28] [INF] [20] Emby.Server.Implementations.HttpServer.WebSocketManager: WS ::ffff:192.168.1.129 request
[09:43:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:01.1288476
[09:43:29] [INF] [1] Main: Startup complete 0:00:22.1983416
[09:43:29] [INF] [12] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /tube-archivist
[09:43:30] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
[09:43:30] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask
[09:43:30] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[09:43:32] [ERR] [27] Emby.Server.Implementations.Plugins.PluginManager: Failed to download image to path /config/data/plugins/Subtitle Extract_2.0.0.0/jellyfin-plugin-subtitleextract.png on disk.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Plugins.PluginManager.GenerateManifest(PackageInfo packageInfo, Version version, String path, PluginStatus status)
[09:43:33] [INF] [23] Emby.Server.Implementations.Updates.InstallationManager: Plugin installed: Playback Reporting 13.0.0.0
[09:43:33] [INF] [23] Emby.Server.Implementations.ApplicationHost: App needs to be restarted.
[09:43:33] [INF] [23] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 2 seconds
[09:43:33] [INF] [23] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[09:43:47] [INF] [23] Emby.Server.Implementations.HttpServer.WebSocketManager: WS ::ffff:192.168.1.163 request
[09:44:03] [INF] [12] Jellyfin.Plugin.PlaybackReporting.Api.PlaybackReportingActivityController: PlaybackReportingActivityController Loaded
[09:44:03] [INF] [12] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Default journal_mode for /config/data/data/playback_reporting.db is delete
[09:44:06] [INF] [29] Jellyfin.Plugin.PlaybackReporting.Api.PlaybackReportingActivityController: PlaybackReportingActivityController Loaded
[09:44:06] [INF] [29] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Default journal_mode for /config/data/data/playback_reporting.db is delete
[09:44:06] [INF] [25] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media2/anime/movies
[09:44:17] [INF] [4] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[09:44:29] [INF] [9] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[09:44:41] [INF] [4] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[09:44:53] [INF] [9] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[09:45:07] [INF] [16] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media2/tv2
[09:45:21] [INF] [20] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media2/movies2
[09:45:40] [INF] [24] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media2/anime/series
[09:46:39] [INF] [15] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/tv
```

**Comment by aptalca** [comment]
Not docker related. We don't touch those

**Comment by hugalafutro** [comment]
Thanks for letting me know I'll take it to Jellyfin.
