### ISSUE TITLE
[BUG] Adding NVIDIA_VISIBLE_DEVICES=all breaks ffmpeg

### ISSUE THREAD

**Issue by TrieBr** [linuxserver/docker-jellyfin#227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I add `NVIDIA_VISIBLE_DEVICES=all` environment variable, as per the instructions, transcoding fails due to missing ffmpeg path:

> FFmpeg path not set.

Navigating To Administration > Dashboard > Playback shows a blank entry for FFMpeg path. Removing the `NVIDIA_VISIBLE_DEVICES` variable fixes the issue.

### Expected Behavior

Playback should continue to work with a valid ffmpeg path when setting `NVIDIA_VISIBLE_DEVICES`

### Steps To Reproduce

```
version: "3"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /tmp/jellyfin/config:/config
      - /tmp/tv:/data/tvshows
      - /tmp/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
```

Remove the line `      - NVIDIA_VISIBLE_DEVICES=all` and then it starts to work again.

### Environment

```markdown
- OS: Docker version 20.10.21, build 20.10.21-0ubuntu1~18.04.3
- How docker service was installed: distro's packagemanager
```

### CPU architecture

arm64

### Docker creation

```bash
docker-compose up ( See steps to reproduce).
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Jellyfin: https://opencollective.com/jellyfin

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[02:55:16] [INF] [1] Main: Jellyfin version: 10.8.13
[02:55:16] [INF] [1] Main: Environment Variables: ["[JELLYFIN_WEB_DIR, /usr/share/jellyfin/web]", "[JELLYFIN_DATA_DIR, /config/data]", "[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_PublishedServerUrl, 192.168.0.5]", "[JELLYFIN_LOG_DIR, /config/log]"]
[02:55:16] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[02:55:16] [INF] [1] Main: Operating system: Linux
[02:55:16] [INF] [1] Main: Architecture: Arm64
[02:55:16] [INF] [1] Main: 64-Bit Process: True
[02:55:16] [INF] [1] Main: User Interactive: True
[02:55:16] [INF] [1] Main: Processor count: 4
[02:55:16] [INF] [1] Main: Program data path: /config/data
[02:55:16] [INF] [1] Main: Web resources path: /usr/share/jellyfin/web
[02:55:16] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[02:55:17] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /config/cache
[02:55:17] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[02:55:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[02:55:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[02:55:17] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[02:55:18] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[02:55:18] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[02:55:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.8.13.0
[02:55:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.8.13.0
[02:55:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.8.13.0
[02:55:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.8.13.0
[02:55:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.8.13.0
[02:55:29] [INF] [1] Main: Kestrel listening on Any IP4 Address
[02:55:30] [WRN] [1] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
[02:55:30] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[02:55:31] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {bed48aea-5f6f-4104-b60c-19345e6e52cb} may be persisted to storage in unencrypted form.
[02:55:31] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[02:55:32] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 2024-01-13 02:00:00.000 +00:00, which is 23:04:27.9461883 from now.
[02:55:32] [ERR] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg validation: The process returned no result
[02:55:32] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Failed version check: /usr/lib/jellyfin-ffmpeg/ffmpeg
[02:55:32] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: 
[02:55:32] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: 40407229368b44e08806fad3198897b5
[02:55:32] [WRN] [17] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://localhost:8096/health to 127.0.0.1 in 0:00:00.8179472 with Status Code 503
[02:55:33] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.9167357
[02:55:33] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[02:55:34] [WRN] [17] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'AccessSchedule' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:55:34] [WRN] [17] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ActivityLog' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:55:34] [WRN] [17] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'CustomItemDisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:55:34] [WRN] [17] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'DisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:55:34] [WRN] [17] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'HomeSection' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:55:34] [WRN] [17] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ImageInfo' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:55:34] [WRN] [17] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ItemDisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:55:34] [WRN] [17] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Permission' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:55:34] [WRN] [17] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Preference' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:55:34] [WRN] [17] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ApiKey' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:55:34] [WRN] [17] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Device' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:55:34] [WRN] [17] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'DeviceOptions' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:55:34] [WRN] [17] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'User' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:55:34] [INF] [12] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /data/tvshows
[02:55:34] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:01.4140876
[02:55:34] [INF] [1] Main: Startup complete 0:00:23.6735343
[02:55:34] [WRN] [17] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://localhost:8096/health to 127.0.0.1 in 0:00:00.9061592 with Status Code 200
[ls.io-init] done.
[02:55:35] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
[02:55:35] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask
[02:55:35] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[02:55:37] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 2 seconds
[02:55:37] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[02:55:38] [INF] [10] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[02:55:38] [ERR] [10] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /videos/e5f788ca-5fe9-71e4-e51a-6c19d694044a/hls1/main/6.ts.
System.ArgumentException: FFmpeg path not set.
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetDynamicSegment(StreamingRequestDto streamingRequest, Int32 segmentId)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetHlsVideoSegment(Guid itemId, String playlistId, Int32 segmentId, String container, Int64 runtimeTicks, Int64 actualSegmentLengthTicks, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions)
   at lambda_method517(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[02:55:38] [WRN] [10] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/videos/e5f788ca-5fe9-71e4-e51a-6c19d694044a/hls1/main/6.ts?DeviceId=TW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyMC4wLjAuMCBTYWZhcmkvNTM3LjM2fDE3MDUwMjIzMzYxODc1&MediaSourceId=e5f788ca5fe971e4e51a6c19d694044a&VideoCodec=h264&AudioCodec=aac,mp3&AudioStreamIndex=1&VideoBitrate=14616000&AudioBitrate=384000&MaxFramerate=23.976025&PlaySessionId=a32432c78a3048939c3830aa78461f5c&api_key=0a706837526646f682fe01bce6e5f61b&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=135e8573c53bdb7b89586dfbf37f98f2&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&hevc-level=150&hevc-videobitdepth=10&hevc-profile=main10&TranscodeReasons=VideoCodecNotSupported,%20AudioCodecNotSupported&runtimeTicks=180000000&actualSegmentLengthTicks=30000000 to 172.18.0.1 in 0:00:01.9565425 with Status Code 400
[02:55:41] [WRN] [13] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Sessions/Playing/Progress to 172.18.0.1 in 0:00:07.6872849 with Status Code 204
[02:55:46] [WRN] [12] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Sessions/Playing/Progress to 172.18.0.1 in 0:00:02.113495 with Status Code 204
[02:55:55] [WRN] [17] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Sessions/Playing/Progress to 172.18.0.1 in 0:00:01.3044007 with Status Code 204
[02:56:15] [WRN] [12] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Sessions/Playing/Progress to 172.18.0.1 in 0:00:00.927557 with Status Code 204
[02:57:15] [WRN] [21] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Sessions/Playing/Progress to 172.18.0.1 in 0:00:00.9865641 with Status Code 204
[02:58:15] [WRN] [21] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Sessions/Playing/Progress to 172.18.0.1 in 0:00:00.6840622 with Status Code 204
[02:59:15] [WRN] [28] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Sessions/Playing/Progress to 172.18.0.1 in 0:00:01.3066274 with Status Code 204
[02:59:29] [INF] [23] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 172.18.0.1 request
[02:59:30] [WRN] [28] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Sessions/Playing/Progress to 172.18.0.1 in 0:00:00.5934214 with Status Code 204
[02:59:31] [INF] [30] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 172.18.0.1 request
[02:59:41] [WRN] [24] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Sessions/Playing/Progress to 172.18.0.1 in 0:00:00.6498251 with Status Code 204
[02:59:41] [INF] [22] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for brad has succeeded.
[02:59:41] [INF] [22] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user brad: 1/0
[02:59:41] [INF] [22] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user cd7e7039-f99e-4d27-b672-448ef00fe4f7
[02:59:41] [WRN] [22] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Users/authenticatebyname to 172.18.0.1 in 0:00:00.7081086 with Status Code 200
[02:59:41] [INF] [28] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 172.18.0.1 request
[02:59:42] [WRN] [27] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/DisplayPreferences/usersettings?userId=cd7e7039f99e4d27b672448ef00fe4f7&client=emby to 172.18.0.1 in 0:00:00.5291735 with Status Code 200
[02:59:51] [WRN] [25] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Sessions/Playing/Progress to 172.18.0.1 in 0:00:00.7548452 with Status Code 204
[03:00:03] [WRN] [33] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Sessions/Playing/Progress to 172.18.0.1 in 0:00:01.5999836 with Status Code 204
[03:00:13] [WRN] [33] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Sessions/Playing/Progress to 172.18.0.1 in 0:00:01.0607996 with Status Code 204
[03:00:18] [INF] [27] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 2 inactive WebSockets.
[03:00:18] [WRN] [33] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Items/8696541497155b92ab1071432eea1d6c/Images/Logo?tag=b6309a29109db189a43c35be8ebf87b3&maxHeight=48&maxWidth=260&quality=90 to 172.18.0.1 in 0:00:00.5687833 with Status Code 200
[03:00:18] [WRN] [33] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Items/8696541497155b92ab1071432eea1d6c/Images/Backdrop?maxWidth=768&tag=562bf666189c2430f6d4b9137f3ac0d0&quality=80 to 172.18.0.1 in 0:00:00.8001295 with Status Code 200
[03:00:23] [WRN] [33] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Sessions/Playing/Progress to 172.18.0.1 in 0:00:00.6983712 with Status Code 204
[03:00:30] [INF] [33] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[03:00:30] [INF] [33] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[03:00:42] [INF] [31] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[03:01:16] [WRN] [29] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Sessions/Playing/Progress to 172.18.0.1 in 0:00:02.0571489 with Status Code 204
[03:02:15] [WRN] [3] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://media:8096/Sessions/Playing/Progress to 172.18.0.1 in 0:00:00.6359461 with Status Code 204
```

**Comment by aptalca** [comment]
That sounds like a jellyfin issue. We don't touch any jellyfin settings with regards to ffmpeg. We just install jellyfin's custom ffmpeg from their repo.

**Comment by ageisen2000** [comment]
Looks like you don't in have your ffmpeg path set correctly. In your server admin options go to playback and set it to /usr/lib/jellyfin-ffmpeg/ffmpeg

See if that fixes it

**Comment by homerr** [comment]
Closing for now as it doesn't appear to be a container based issue. Come join us in Discord if more help is needed.
