### ISSUE TITLE
[Issue]: Cannot scan library even after increasing max_user_watches limit

### ISSUE THREAD

**Issue by Maypul** [linuxserver/docker-jellyfin#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello! I encountered issue where I scanned my library and it stopped nearly instantly, at 10%. Checking the container logs it showed that it reached inotify watcher 8192 limit, so I increased it on my Synology NAS, confirmed it is set and rebooted device for good measure.

After reboot it is confirmed still set, have a script to set it up each reboot just in case.

cat /proc/sys/fs/inotify/max_user_watches
3276800

Now, libraries I have not scanned before this change seems to work and scan. But the one library I did scan, the scan still breaks at 10%.

Jellyfin container also confirms it inherited the settings:
root@jellyfin:/# cat /proc/sys/fs/inotify/max_user_watches                       
3276800

### Expected Behavior

Library would start scanning

### Steps To Reproduce

Enviroment: DS1821+, DSM 7.2.1-69057 Update 4,1 Library of 1 movie, second library of ~1500 movies, third library of 50 series (so ton of episodes), fourth library of 200 movies.
Folder structure is usually like: main share -> movie folder -> movie file, subtitle file, 5 pictures file, also .actors folder with some actors images. Series have per season folder also.
Encounter error showing max_user_watches limit is reached
Fix the issue, try rescanning library once more.
Library still does not scan.

### Environment

```markdown
- OS:Synology OS
- Model: DS1821+
- Version: DSM 7.2.1-69057 Update 4
- Docker was installed from Synology store, container and the rest from CLI
```

### CPU architecture

x86-64

### Docker creation

```bash
jellyfin:
    container_name: Jellyfin
    hostname: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    privileged: false
    read_only: false
    networks:
      home:
    security_opt:
      - no-new-privileges:true
    volumes:
      - $SHR_DOCKER/Jellyfin/Config:/config:rw
      - $SHR_DOCKER/Jellyfin/Cache:/cache:rw
      - $SHR_FANEDITS:/Media/Fanedits:ro
      - $SHR_MOVIES:/Media/Movies:ro
      - $SHR_SHORTS:/Media/Shorts:ro
      - $SHR_SERIES:/Media/Series:ro
    environment:
      PUID: $PUID_DOCKERUSER
      PGID: $PGID_USERS
      TZ: $TZ
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin-rtr.entrypoints: https
      traefik.http.routers.jellyfin-rtr.rule: Host(`films.$DOMAINNAME`)
      traefik.http.routers.jellyfin-rtr.tls: true
      traefik.http.routers.jellyfin-rtr.middlewares: chain-auth-disabled@file,middlewares-csp-jellyfin@file
      traefik.http.routers.jellyfin-rtr.service: jellyfin-svc
      traefik.http.services.jellyfin-svc.loadbalancer.server.port: 8096
```

### Container logs

```bash
2024/02/16 21:01:29	stdout	   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalStreamsAsync(Video video, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache, CancellationToken cancellationToken)
2024/02/16 21:01:29	stdout	   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
2024/02/16 21:01:29	stdout	   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
2024/02/16 21:01:29	stdout	MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
2024/02/16 21:01:29	stdout	[21:01:29] [ERR] [28] MediaBrowser.Providers.MediaInfo.SubtitleResolver: Error getting external streams from /Media/Series/Breaking Bad (2008)/Season 05/Breaking Bad S05E08.eng.srt
2024/02/16 21:01:29	stderr	file:/Media/Series/Breaking Bad (2008)/Season 05/Breaking Bad S05E08.eng.srt: Invalid data found when processing input
2024/02/16 21:01:28	stdout	   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalStreamsAsync(Video video, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache, CancellationToken cancellationToken)
2024/02/16 21:01:28	stdout	   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
2024/02/16 21:01:28	stdout	   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
2024/02/16 21:01:28	stdout	MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
2024/02/16 21:01:28	stdout	[21:01:28] [ERR] [28] MediaBrowser.Providers.MediaInfo.SubtitleResolver: Error getting external streams from /Media/Series/Breaking Bad (2008)/Season 05/Breaking Bad S05E05.eng.srt
2024/02/16 21:01:28	stderr	file:/Media/Series/Breaking Bad (2008)/Season 05/Breaking Bad S05E05.eng.srt: Invalid data found when processing input
2024/02/16 21:00:41	stdout	[21:00:41] [INF] [31] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 10.0.0.25 request
2024/02/16 21:00:40	stdout	[21:00:40] [INF] [25] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 10.0.0.25 closed
2024/02/16 21:00:39	stdout	[21:00:39] [INF] [17] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 10.0.0.25 request
2024/02/16 20:59:09	stdout	[20:59:09] [INF] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
2024/02/16 20:59:09	stdout	[20:59:09] [INF] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 11 seconds
2024/02/16 20:59:07	stdout	   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken)
2024/02/16 20:59:07	stdout	   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
2024/02/16 20:59:07	stdout	   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2024/02/16 20:59:07	stdout	   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2024/02/16 20:59:07	stdout	   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2024/02/16 20:59:07	stdout	   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024/02/16 20:59:07	stdout	   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024/02/16 20:59:07	stdout	   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2024/02/16 20:59:07	stdout	   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024/02/16 20:59:07	stdout	   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
2024/02/16 20:59:07	stdout	   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
2024/02/16 20:59:07	stdout	   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024/02/16 20:59:07	stdout	   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024/02/16 20:59:07	stdout	   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
2024/02/16 20:59:07	stdout	   --- End of inner exception stack trace ---
2024/02/16 20:59:07	stdout	   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
2024/02/16 20:59:07	stdout	   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
2024/02/16 20:59:07	stdout	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
2024/02/16 20:59:07	stdout	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2024/02/16 20:59:07	stdout	 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
2024/02/16 20:59:07	stdout	System.Net.Http.HttpRequestException: Resource temporarily unavailable (repo.jellyfin.org:443)
2024/02/16 20:59:07	stdout	[20:59:07] [ERR] [25] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: https://repo.jellyfin.org/releases/plugin/manifest-stable.json
2024/02/16 20:58:57	stdout	[20:58:57] [INF] [14] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
2024/02/16 20:58:57	stdout	[20:58:57] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask
2024/02/16 20:58:57	stdout	[20:58:57] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
2024/02/16 20:58:55	stdout	[ls.io-init] done.
2024/02/16 20:58:55	stdout	[20:58:55] [INF] [1] Main: Startup complete 0:00:09.3924709
2024/02/16 20:58:55	stdout	[20:58:55] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.280679
2024/02/16 20:58:55	stdout	[20:58:55] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /Media/Fanedits
2024/02/16 20:58:55	stdout	[20:58:55] [INF] [13] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /Media/Series
2024/02/16 20:58:55	stdout	[20:58:55] [INF] [14] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /Media/Shorts
2024/02/16 20:58:55	stdout	[20:58:55] [INF] [16] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /Media/Movies
2024/02/16 20:58:55	stdout	[20:58:55] [INF] [16] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path /Media/Movies
2024/02/16 20:58:55	stdout	[20:58:55] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path /Media/Fanedits
2024/02/16 20:58:55	stdout	[20:58:55] [INF] [13] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path /Media/Series
2024/02/16 20:58:55	stdout	[20:58:55] [INF] [14] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path /Media/Shorts
2024/02/16 20:58:55	stdout	System.IO.IOException: The configured user limit (8192) on the number of inotify watches has been reached, or the operating system failed to allocate a required resource.
2024/02/16 20:58:55	stdout	[20:58:55] [ERR] [16] Emby.Server.Implementations.IO.LibraryMonitor: Error in Directory watcher for: /Media/Movies
2024/02/16 20:58:55	stdout	System.IO.IOException: The configured user limit (8192) on the number of inotify watches has been reached, or the operating system failed to allocate a required resource.
2024/02/16 20:58:55	stdout	[20:58:55] [ERR] [17] Emby.Server.Implementations.IO.LibraryMonitor: Error in Directory watcher for: /Media/Fanedits
2024/02/16 20:58:55	stdout	System.IO.IOException: The configured user limit (8192) on the number of inotify watches has been reached, or the operating system failed to allocate a required resource.
2024/02/16 20:58:55	stdout	[20:58:55] [ERR] [13] Emby.Server.Implementations.IO.LibraryMonitor: Error in Directory watcher for: /Media/Series
2024/02/16 20:58:55	stdout	System.IO.IOException: The configured user limit (8192) on the number of inotify watches has been reached, or the operating system failed to allocate a required resource.
2024/02/16 20:58:55	stdout	[20:58:55] [ERR] [14] Emby.Server.Implementations.IO.LibraryMonitor: Error in Directory watcher for: /Media/Shorts
2024/02/16 20:58:55	stdout	[20:58:55] [WRN] [4] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'User' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024/02/16 20:58:55	stdout	[20:58:55] [WRN] [4] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'DeviceOptions' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024/02/16 20:58:55	stdout	[20:58:55] [WRN] [4] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Device' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024/02/16 20:58:55	stdout	[20:58:55] [WRN] [4] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ApiKey' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024/02/16 20:58:55	stdout	[20:58:55] [WRN] [4] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Preference' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024/02/16 20:58:55	stdout	[20:58:55] [WRN] [4] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Permission' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024/02/16 20:58:55	stdout	[20:58:55] [WRN] [4] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ItemDisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024/02/16 20:58:55	stdout	[20:58:55] [WRN] [4] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ImageInfo' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024/02/16 20:58:55	stdout	[20:58:55] [WRN] [4] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'HomeSection' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024/02/16 20:58:55	stdout	[20:58:55] [WRN] [4] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'DisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024/02/16 20:58:55	stdout	[20:58:55] [WRN] [4] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'CustomItemDisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024/02/16 20:58:55	stdout	[20:58:55] [WRN] [4] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ActivityLog' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024/02/16 20:58:55	stdout	[20:58:55] [WRN] [4] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'AccessSchedule' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
2024/02/16 20:58:54	stdout	[20:58:54] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
2024/02/16 20:58:54	stdout	[20:58:54] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.1945228
2024/02/16 20:58:54	stdout	[20:58:54] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: 25e809b4a4b1475d9058d2d38380c724
2024/02/16 20:58:54	stdout	[20:58:54] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: /usr/lib/jellyfin-ffmpeg/ffmpeg
2024/02/16 20:58:54	stdout	[20:58:54] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
2024/02/16 20:58:54	stdout	[20:58:54] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "hwupload_vaapi", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
2024/02/16 20:58:54	stdout	[20:58:54] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
2024/02/16 20:58:54	stdout	[20:58:54] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
2024/02/16 20:58:54	stdout	[20:58:54] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 5.1.4
2024/02/16 20:58:54	stdout	[20:58:54] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
2024/02/16 20:58:54	stdout	[20:58:54] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {25f9f89e-45c7-47cc-875c-6e03247f3f84} may be persisted to storage in unencrypted form.
2024/02/16 20:58:53	stdout	[20:58:53] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
2024/02/16 20:58:53	stdout	[20:58:53] [WRN] [1] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
2024/02/16 20:58:53	stdout	[20:58:53] [INF] [1] Main: Kestrel listening on Any IP4 Address
2024/02/16 20:58:53	stdout	[20:58:53] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.8.13.0
2024/02/16 20:58:53	stdout	[20:58:53] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.8.13.0
2024/02/16 20:58:53	stdout	[20:58:53] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.8.13.0
2024/02/16 20:58:53	stdout	[20:58:53] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.8.13.0
2024/02/16 20:58:53	stdout	[20:58:53] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.8.13.0
2024/02/16 20:58:53	stdout	[20:58:53] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TheTVDB 10.0.0.0
2024/02/16 20:58:53	stdout	[20:58:53] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: SSO-Auth 3.4.0.0
2024/02/16 20:58:53	stdout	[20:58:53] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: LDAP-Auth 16.0.0.0
2024/02/16 20:58:47	stdout	[20:58:47] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
2024/02/16 20:58:47	stdout	[20:58:47] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
2024/02/16 20:58:47	stdout	[20:58:47] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
2024/02/16 20:58:47	stdout	[20:58:47] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
2024/02/16 20:58:47	stdout	[20:58:47] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
2024/02/16 20:58:47	stdout	[20:58:47] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Tvdb, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TheTVDB_10.0.0.0/Jellyfin.Plugin.Tvdb.dll
2024/02/16 20:58:47	stdout	[20:58:47] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly TvDbSharper, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TheTVDB_10.0.0.0/TvDbSharper.dll
2024/02/16 20:58:47	stdout	[20:58:47] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly IdentityModel.OidcClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5580d04c1b6c37c1 from /config/data/plugins/SSO Authentication_3.4.0.0/IdentityModel.OidcClient.dll
2024/02/16 20:58:47	stdout	[20:58:47] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly SSO-Auth, Version=3.4.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/SSO Authentication_3.4.0.0/SSO-Auth.dll
2024/02/16 20:58:47	stdout	[20:58:47] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly IdentityModel, Version=5.2.0.0, Culture=neutral, PublicKeyToken=e7877f4675df049f from /config/data/plugins/SSO Authentication_3.4.0.0/IdentityModel.dll
2024/02/16 20:58:47	stdout	[20:58:47] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Novell.Directory.Ldap.NETStandard, Version=3.6.0.0, Culture=neutral, PublicKeyToken=510c34e9dec7f86f from /config/data/plugins/LDAP Authentication_16.0.0.0/Novell.Directory.Ldap.NETStandard.dll
2024/02/16 20:58:47	stdout	[20:58:47] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly LDAP-Auth, Version=16.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/LDAP Authentication_16.0.0.0/LDAP-Auth.dll
2024/02/16 20:58:47	stdout	[20:58:47] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
2024/02/16 20:58:47	stdout	[20:58:47] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /config/cache
2024/02/16 20:58:46	stdout	[20:58:46] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
2024/02/16 20:58:46	stdout	[20:58:46] [INF] [1] Main: Web resources path: /usr/share/jellyfin/web
2024/02/16 20:58:46	stdout	[20:58:46] [INF] [1] Main: Program data path: /config/data
2024/02/16 20:58:46	stdout	[20:58:46] [INF] [1] Main: Processor count: 8
2024/02/16 20:58:46	stdout	[20:58:46] [INF] [1] Main: User Interactive: True
2024/02/16 20:58:46	stdout	[20:58:46] [INF] [1] Main: 64-Bit Process: True
2024/02/16 20:58:46	stdout	[20:58:46] [INF] [1] Main: Architecture: X64
2024/02/16 20:58:46	stdout	[20:58:46] [INF] [1] Main: Operating system: Linux
2024/02/16 20:58:46	stdout	[20:58:46] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
2024/02/16 20:58:46	stdout	[20:58:46] [INF] [1] Main: Environment Variables: ["[JELLYFIN_WEB_DIR, /usr/share/jellyfin/web]", "[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_DATA_DIR, /config/data]"]
2024/02/16 20:58:46	stdout	[20:58:46] [INF] [1] Main: Jellyfin version: 10.8.13
2024/02/16 20:58:45	stdout	[custom-init] No custom files found, skipping...
2024/02/16 20:58:45	stdout	
2024/02/16 20:58:45	stdout	───────────────────────────────────────
2024/02/16 20:58:45	stdout	User GID:    100
2024/02/16 20:58:45	stdout	User UID:    1027
2024/02/16 20:58:45	stdout	
2024/02/16 20:58:45	stdout	───────────────────────────────────────
2024/02/16 20:58:45	stdout	GID/UID
2024/02/16 20:58:45	stdout	───────────────────────────────────────
2024/02/16 20:58:45	stdout	
2024/02/16 20:58:45	stdout	https://www.linuxserver.io/donate/
2024/02/16 20:58:45	stdout	To support LSIO projects visit:
2024/02/16 20:58:45	stdout	
2024/02/16 20:58:45	stdout	Jellyfin: https://opencollective.com/jellyfin
2024/02/16 20:58:45	stdout	To support the app dev(s) visit:
2024/02/16 20:58:45	stdout	
2024/02/16 20:58:45	stdout	───────────────────────────────────────
2024/02/16 20:58:45	stdout	   Brought to you by linuxserver.io
2024/02/16 20:58:45	stdout	
2024/02/16 20:58:45	stdout	      ╚══════╝╚══════╝╚═╝ ╚═════╝
2024/02/16 20:58:45	stdout	      ███████╗███████║██║╚██████╔╝
2024/02/16 20:58:45	stdout	      ██║     ╚════██║██║██║   ██║
2024/02/16 20:58:45	stdout	      ██║     ███████╗██║██║   ██║
2024/02/16 20:58:45	stdout	      ██║     ██╔════╝██║██╔═══██╗
2024/02/16 20:58:45	stdout	      ██╗     ███████╗██╗ ██████╗
2024/02/16 20:58:45	stdout	
2024/02/16 20:58:45	stdout	───────────────────────────────────────
2024/02/16 20:58:45	stdout	usermod: no changes
2024/02/16 20:58:45	stdout	[migrations] no migrations found
2024/02/16 20:58:45	stdout	[migrations] started
```

**Comment by Maypul** [comment]
Update: It seems to be scanning new movies, but the one that triggered this error is unscanable. I have tried removing it and readding, once, managing to get following message in log: 
2024/02/18 11:11:17	stdout	[11:11:17] [INF] [36] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Movie, Name: Smokin' Aces, Path: /Media/Movies/Smokin' Aces (2006)/Smokin' Aces.mkv, Id: f35c8bec-46b0-ffb3-c948-c1f39d66f4bb 
(But the movie was never added to Jellyfin) and even after that, readding the folder with movie does not make it visible in the Jellyfin.

**Comment by homerr** [comment]
Given everything else imported bar this file, I would suggest there is a problem with the file or there may be some strange characters in the file name. Unsure, but either way, I am going to close this as there are no issues with the actual container.
