### ISSUE TITLE
[BUG] Nightly segfaults on arm64 in .NET JIT

### ISSUE THREAD

**Issue by danog** [linuxserver/docker-jellyfin#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

jellyfin segfaults randomly, without playing anything:

```
#0  0x0000ffff504edf78 in ?? () from /usr/lib/jellyfin/bin/libclrjit.so
#1  0x0000ffff50322da0 in ?? () from /usr/lib/jellyfin/bin/libclrjit.so
#2  0x0000ffff50311508 in ?? () from /usr/lib/jellyfin/bin/libclrjit.so
#3  0x0000ffff50319ff4 in ?? () from /usr/lib/jellyfin/bin/libclrjit.so
#4  0x0000ffff503104d0 in ?? () from /usr/lib/jellyfin/bin/libclrjit.so
#5  0x0000ffff503337f4 in ?? () from /usr/lib/jellyfin/bin/libclrjit.so
#6  0x0000ffff50336944 in ?? () from /usr/lib/jellyfin/bin/libclrjit.so
#7  0x0000ffff5033b198 in ?? () from /usr/lib/jellyfin/bin/libclrjit.so
#8  0x0000ffff93d9b310 in ?? () from /usr/lib/jellyfin/bin/libcoreclr.so
#9  0x0000ffff93d9b40c in ?? () from /usr/lib/jellyfin/bin/libcoreclr.so
#10 0x0000ffff93d9be00 in ?? () from /usr/lib/jellyfin/bin/libcoreclr.so
#11 0x0000ffff93dd3a70 in ?? () from /usr/lib/jellyfin/bin/libcoreclr.so
#12 0x0000ffff93dd3724 in ?? () from /usr/lib/jellyfin/bin/libcoreclr.so
#13 0x0000ffff93dd2f90 in ?? () from /usr/lib/jellyfin/bin/libcoreclr.so
#14 0x0000ffff93dd2b38 in ?? () from /usr/lib/jellyfin/bin/libcoreclr.so
#15 0x0000ffff93e036d8 in ?? () from /usr/lib/jellyfin/bin/libcoreclr.so
#16 0x0000ffff93e02cc4 in ?? () from /usr/lib/jellyfin/bin/libcoreclr.so
#17 0x0000ffff93e02510 in ?? () from /usr/lib/jellyfin/bin/libcoreclr.so
#18 0x0000ffff93e02304 in ?? () from /usr/lib/jellyfin/bin/libcoreclr.so
#19 0x0000ffff93dfeacc in ?? () from /usr/lib/jellyfin/bin/libcoreclr.so
#20 0x0000ffff93dff088 in ?? () from /usr/lib/jellyfin/bin/libcoreclr.so
#21 0x0000ffff93e02204 in ?? () from /usr/lib/jellyfin/bin/libcoreclr.so
#22 0x0000ffff9415a568 in ?? () from /usr/lib/jellyfin/bin/libcoreclr.so
#23 0x0000ffff9441d5c8 in futex_wait (private=0, expected=<optimized out>, futex_word=0xffbe951bf4fc) at ../sysdeps/nptl/futex-internal.h:146
#24 futex_wait_simple (private=0, expected=<optimized out>, futex_word=0xffbe951bf4fc) at ../sysdeps/nptl/futex-internal.h:177
#25 __condvar_acquire_lock (private=0, cond=0xffbe47ffc7ee) at ./nptl/pthread_cond_common.c:140
#26 __condvar_cancel_waiting (cond=0xffbe47ffc7ee, seq=281192716814319, g=8448288, private=0) at ./nptl/pthread_cond_wait.c:85
#27 0x0000ffff94485d1c in __get_nprocs_sched () at ../sysdeps/unix/sysv/linux/getsysstats.c:35
#28 0x000000000080e920 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

### Steps To Reproduce

Run jellyfin on nightly

### Environment

```markdown
- OS: Manjaro
- How docker service was installed: distro's package manager
```

### CPU architecture

arm64

### Docker creation

```bash
jellyfin:
    image: lscr.io/linuxserver/jellyfin:nightly
    devices:
      - /dev/video10
      - /dev/video11
      - /dev/video12
      - /dev/video13
      - /dev/video14
      - /dev/video15
      - /dev/video16
      - /dev/video18
      - /dev/video20
      - /dev/video21
      - /dev/video22
      - /dev/video23
      - /dev/video31
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - JELLYFIN_PublishedServerUrl=192.168.69.3
    volumes:
      - /media/storage/persist/jellyfin:/config
      - /media/storage/persist/music:/music:ro
      - /media:/media:ro
    restart: unless-stopped
    ports:
      - 192.168.69.3:8096:8096
      - 192.168.69.3:7359:7359/udp
      - 192.168.69.3:1900:1900/udp
    networks:
      - frontend
```
```


### Container logs

No logs during segfault.

**Comment by homerr** [comment]
This is highly likely to be an upstream issue unfortunately with it being nightly. I'd recommend going to them, but this is a few weeks ago now so probably already resolved.
