### ISSUE TITLE
Recording fails with ports remapped

### ISSUE THREAD

**Issue by danadux** [linuxserver/docker-jellyfin#39]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
With Live TV tuner setup, and XMLTV listings imported, selecting an episode from the guide and choosing Series Recording should create a Series Recording. 

## Current Behavior
Following the steps above, clicking Series Recording results in no web response. 

## Steps to Reproduce

1. Startup Jellyfin with port remapped e.g. ports: 9016:8096
2. Enable Live TV. Enable guide.
3. Create series recording. Observe silent failure.
4. In Jellyfin Admin Dashboard Networking, edit HTTP port to 9016.
5. Relaunch docker container with port mapping 9016:9016
6. Create series recording successfully.

## Environment
**OS:**  Ubuntu 19.04 LTS
**CPU architecture:** x86_64
**How docker service was installed:**      
Docker-compose using official docker repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu"

## Command used to create docker container (run/create/compose/screenshot)
jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    runtime: nvidia
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=<022> #optional
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${CONFIG}/emby:/config
      - ${MOVIES}:/movies
      - ${TV}:/tv
      - ${PHOTOS}:/photos
      - ${VIDEOS}:/videos
      - ${MUSIC}:/music
      - ${DOWNLOADS}/emby_tmp:/transcode
      - ${DOCKER}/compress:/compress
    ports:
      - 9016:8096
      - 8920:8920 #optional
    labels:
      - traefik.enable=false
      - traefik.backend=jellyfin
      - traefik.frontend.rule=Host:jellyfin.domain.tld
    restart: unless-stopped

## Docker logs

[20:12:27] [ERR] [54] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http:/localIP:9016/LiveTv/Timers/Defaults?programId=HEX##
System.Collections.Generic.KeyNotFoundException: No service with the name '' can be found.
   at Emby.Server.Implementations.LiveTv.LiveTvManager.GetService(String name)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.GetService(LiveTvChannel item)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.GetService(LiveTvProgram item)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.GetNewTimerDefaultsInternal(CancellationToken cancellationToken, LiveTvProgram program)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.GetNewTimerDefaults(String programId, CancellationToken cancellationToken)
   at MediaBrowser.Api.LiveTv.LiveTvService.Get(GetDefaultTimer request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

**Comment by aptalca** [comment]
That looks like a jellyfin issue where it expects a hardcoded port with the request?

**Comment by danadux** [comment]
Error on my side - Emby and Jellyfin configs were stepping on each other. Moved config to a distinct directory and the problem was resolved.
