### ISSUE TITLE
official image with owned direct as set with correct puid/pguid still cause Access to the path '/config/data' is denied

### ISSUE THREAD

**Issue by kopax** [linuxserver/docker-jellyfin#63]
## Expected Behavior

Using the `docker-compose.yml` from the `README.md`, I can't start the server.

## Current Behavior

I am having the service that crash due to permissions issues.

and `/config/data` owned as expected to uid/guid 1000 as set with the environment PUID/GUID

## Steps to Reproduce

1. Copy paste `docker-compose.yml` from readme
2. Set correct permissions
3. Set correct environment when deploying with docker
4. Start the docker service, notice the error in the docker log

## Environment
**OS:**       Debian Buster, Linux 5.7 bpo
**CPU architecture:** amd64
**How docker service was installed:** As described in the docker documentation for Debian

## Command used to create docker container (run/create/compose/screenshot)

Using `docker-compose.yml`

## Docker logs

```bash
System.UnauthorizedAccessException: Access to the path '/config/data' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/config/data' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
Unhandled Exception
System.UnauthorizedAccessException: Access to the path '/config/data' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/config/data' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
Unhandled Exception
System.UnauthorizedAccessException: Access to the path '/config/data' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/config/data' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

````

**Comment by kopax** [comment]
Thank you bot, issue template link is dead. Is this repo still under maintenance? Does anybody have a replacement to offer ?

**Comment by Roxedus** [comment]
A fix for the bot is in the works. You followed the template, although the actual compose you used would be appreciated.

**Comment by kopax** [comment]
I finally was able to start the container by removing the volume `  -v /path/to/library:/config`,

The command used to start this container is now:


```bash
docker run
  --privileged \
  -e PGID=1000 \
  -e PUID=1000 \
  -e TZ=Europe/Paris \
  -v /srv/transmission/downloads/tvshows:/data/tvshows:rw \
  -v /srv/transmission/downloads/movies:/data/movies:rw \
  --net bridge
  -p 31363:8096/tcp \
  --device=/dev/dri:/dev/dri \
  linuxserver/jellyfin:latest

```

Did I had to configure anything in config or can I just use the default configuration?

**Comment by Roxedus** [comment]
/config houses all your metadata and library information. So once you recreate the container, that info is gone. Where is `/srv`?

**Comment by j0nnymoe** [comment]
@kopax the issue you're experiencing here is the same issue you're having here https://github.com/linuxserver/docker-transmission/issues/126 - don't use remote mounts for the `/config` folders, unless you get the permissions right, they aren't going to work. In jellyfin's case, there is also another issue that it uses SQLite which just hates remote mounts.

**Comment by kopax** [comment]
Thanks, that definitelly solved the starting issue.

However, I have uploaded in the mounted movie directory a mkv to see if it appear and it does not. I am also testing flexget but I have poor knowledge of the tools and still learn. 

Do you know how transmissions, flexget and jellyfin can work together (all from linux server) to view and pull torrents?

I am concerns with the shared download directory and the [configuration](https://flexget.com/Cookbook/Transmission)

**Comment by j0nnymoe** [comment]
> However, I have uploaded in the mounted movie directory a mkv to see if it appear and it does not. I am also testing flexget but I have poor knowledge of the tools and still learn.

This is likely due to permissions issues and won't be due to the container.

> Do you know how transmissions, flexget and jellyfin can work together (all from linux server) to view and pull torrents?
This is something I'm sure you can find plenty of information about how to do online from the usual places.
